#!/usr/bin/env python3
"""data_usage.py — produce a per-symbol usage inventory for RAM globals
(src/globals.c, addresses derived from src/globals.s.bak) and ROM data
(src/romdata.c, addresses from inline comments).

Writes build/data_usage.md sorted by address. Each row lists the symbol's
address, declared type/size, the count and a short summary of every C
callsite (file:line + access kind), plus its immediate neighbors.

Run this whenever you've renamed/retyped a global so the inventory stays
in sync with reality.
"""
from __future__ import annotations
import os, re, sys
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / "src"
INC  = ROOT / "include"

# Files that are themselves the *definition* of these symbols and shouldn't
# be reported as callers.
EXCLUDE_FILES = {
    SRC / "globals.c", SRC / "romdata.c",
    INC / "globals.h", INC / "all_headers.h",
}

ACCESS_KINDS = (
    ("write_assign",  re.compile(r"\b{name}\b\s*=(?!=)")),
    ("compound_op",   re.compile(r"\b{name}\b\s*(?:\+=|-=|\*=|/=|\|=|&=|\^=|<<=|>>=|\+\+|--)")),
    ("preincr",       re.compile(r"(?:\+\+|--)\s*\b{name}\b")),
    ("indexed",       re.compile(r"\b{name}\b\s*\[")),
    ("address_of",    re.compile(r"&\s*\b{name}\b")),
    ("cast_through",  re.compile(r"\(\s*[\w\s\*]+\s*\)\s*\b{name}\b")),
    ("member_access", re.compile(r"\b{name}\b\s*(?:\.|->)")),
)

_TYPE_SIZES = {"uint8_t": 1, "int8_t": 1,
               "uint16_t": 2, "int16_t": 2,
               "uint32_t": 4, "int32_t": 4}

def parse_globals_c(path: Path) -> list[tuple[str, int, int]]:
    """Returns [(name, addr, size)] from globals.c, using the inline
    `/* 0xXXXX */` comment on each declaration line. Source order matches
    intended RAM layout (note: ch38 may reorder at link time)."""
    out = []
    decl_re = re.compile(
        r"^\s*(?:volatile\s+)?(?:uint8_t|uint16_t|uint32_t|int8_t|int16_t|int32_t)"
        r"\s*\*?\s*(\w+)\s*(?:\[(\d+)\])?\s*;\s*/\*\s*0x([0-9A-Fa-f]+)"
    )
    type_re = re.compile(
        r"^\s*(?:volatile\s+)?(uint8_t|uint16_t|uint32_t|int8_t|int16_t|int32_t)"
    )
    for line in path.read_text().splitlines():
        m = decl_re.match(line)
        if not m: continue
        name, count, addrhex = m.group(1), m.group(2), m.group(3)
        addr = int(addrhex, 16)
        tm = type_re.match(line)
        elem_size = _TYPE_SIZES.get(tm.group(1), 1) if tm else 1
        size = int(count) * elem_size if count else elem_size
        if "*" in line.split(name)[0].split(";")[0]:
            size = 2  # pointer in 300HN normal mode
        out.append((name, addr, size))
    out.sort(key=lambda t: t[1])
    return out

def parse_romdata_c(path: Path) -> list[tuple[str, int, int]]:
    """Returns [(name, addr, size)] from romdata.c using the /* 0xXXXX */
    comment immediately above each declaration."""
    text = path.read_text()
    out = []
    for m in re.finditer(
        r"/\*\s*0x([0-9A-Fa-f]+)[^*]*\*/\s*\nconst\s+uint8_t\s+(\w+)\s*\[(\d+)\]",
        text,
    ):
        addr = int(m.group(1), 16)
        name = m.group(2)
        size = int(m.group(3))
        out.append((name, addr, size))
    out.sort(key=lambda t: t[1])
    return out

def collect_c_files(root: Path) -> list[Path]:
    return [p for p in root.rglob("*.c") if p not in EXCLUDE_FILES]

def find_callsites(symbols: list[str], files: list[Path]) -> dict[str, list[tuple[Path, int, str, set[str]]]]:
    """Return name -> [(file, line, line_text, kinds_set)]."""
    out: dict[str, list] = defaultdict(list)
    word_re = {n: re.compile(rf"(?<!\w){re.escape(n)}(?!\w)") for n in symbols}
    kind_re = {
        n: [(k, re.compile(p.pattern.format(name=re.escape(n)))) for k, p in ACCESS_KINDS]
        for n in symbols
    }
    for fp in files:
        try:
            text = fp.read_text()
        except UnicodeDecodeError:
            continue
        lines = text.splitlines()
        for n in symbols:
            for i, ln in enumerate(lines, 1):
                if word_re[n].search(ln):
                    kinds = {k for k, kr in kind_re[n] if kr.search(ln)}
                    if not kinds:
                        kinds = {"read"}
                    out[n].append((fp, i, ln.strip(), kinds))
    return out

def adjacent_summary(table: list[tuple[str,int,int]], idx: int) -> str:
    parts = []
    if idx > 0:
        n, a, s = table[idx - 1]
        parts.append(f"prev: {n} @ 0x{a:04X}+{s}")
    if idx + 1 < len(table):
        n, a, s = table[idx + 1]
        parts.append(f"next: {n} @ 0x{a:04X}+{s}")
    return "; ".join(parts)

def render(ram: list, rom: list, callsites: dict) -> str:
    lines = ["# Data Usage Inventory",
             "",
             "Auto-generated by `scripts/data_usage.py`. Sorted by address.",
             "Use this to pick rename targets: low call counts are easy wins;",
             "clusters of adjacent vars touched by the same function are likely struct fields.",
             ""]
    for title, table in (("RAM globals (section B)", ram), ("ROM data (section CP)", rom)):
        lines.append(f"## {title}")
        lines.append("")
        for i, (name, addr, size) in enumerate(table):
            cs = callsites.get(name, [])
            kinds = sorted({k for *_, ks in cs for k in ks})
            files_touched = sorted({fp.relative_to(ROOT).as_posix() for fp, *_ in cs})
            lines.append(f"### `{name}` — 0x{addr:04X}, {size} byte(s)")
            lines.append(f"- **callers**: {len(cs)}  |  **files**: {len(files_touched)}  |  **patterns**: {', '.join(kinds) or 'none'}")
            lines.append(f"- **adjacent**: {adjacent_summary(table, i) or '(edge)'}")
            if cs:
                lines.append(f"- **sites**:")
                for fp, ln, txt, ks in cs[:8]:  # cap per symbol
                    rel = fp.relative_to(ROOT).as_posix()
                    snippet = txt if len(txt) <= 100 else txt[:97] + "..."
                    lines.append(f"  - `{rel}:{ln}` [{','.join(sorted(ks))}] — `{snippet}`")
                if len(cs) > 8:
                    lines.append(f"  - ... and {len(cs)-8} more")
            lines.append("")
    return "\n".join(lines)

def parse_aliases(path: Path) -> list[tuple[str, str]]:
    """Returns [(alias, target_expr)] from #define lines in globals.h."""
    out = []
    for line in path.read_text().splitlines():
        m = re.match(r"\s*#define\s+(\w+)\s+(.+?)(?:\s*/\*.*)?$", line)
        if m:
            out.append((m.group(1), m.group(2).strip()))
    return out

def render_aliases(aliases: list[tuple[str,str]], cs: dict) -> str:
    lines = ["## Macro aliases (globals.h)", ""]
    for alias, expr in aliases:
        sites = cs.get(alias, [])
        lines.append(f"### `{alias}` → `{expr}`")
        lines.append(f"- **callers**: {len(sites)}")
        if sites:
            for fp, ln, txt, ks in sites[:6]:
                rel = fp.relative_to(ROOT).as_posix()
                snippet = txt if len(txt) <= 100 else txt[:97] + "..."
                lines.append(f"  - `{rel}:{ln}` [{','.join(sorted(ks))}] — `{snippet}`")
            if len(sites) > 6:
                lines.append(f"  - ... and {len(sites)-6} more")
        lines.append("")
    return "\n".join(lines)

def main():
    ram = parse_globals_c(SRC / "globals.c")
    rom = parse_romdata_c(SRC / "romdata.c")
    aliases = parse_aliases(INC / "globals.h")
    alias_names = [a for a, _ in aliases]
    all_names = [n for n, *_ in ram] + [n for n, *_ in rom] + alias_names
    files = collect_c_files(SRC)
    cs = find_callsites(all_names, files)
    out_path = ROOT / "build" / "data_usage.md"
    out_path.parent.mkdir(exist_ok=True)
    out_path.write_text(render(ram, rom, cs) + "\n" + render_aliases(aliases, cs))

    no_callers = [n for n, *_ in ram + rom if not cs.get(n)]
    one_caller = [n for n, *_ in ram + rom if len(cs.get(n, [])) == 1]
    print(f"wrote {out_path}", file=sys.stderr)
    print(f"  total symbols: {len(all_names)} ({len(ram)} RAM + {len(rom)} ROM + {len(aliases)} aliases)", file=sys.stderr)
    print(f"  unused (0 callers): {len(no_callers)}", file=sys.stderr)
    print(f"  single-use (1 caller): {len(one_caller)}", file=sys.stderr)

if __name__ == "__main__":
    main()
